### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by HongminWu** [brentyi/multimodalfilter#2]
I tried to run the file scripts/bash_scripts/train_push.sh, but got the following error
-- can't open file 'scripts/push_task/finetune_ekf.py': [Err no 2] No such file or directory.

Would you upload those supplemental files for full implementation?

**Comment by brentyi** [comment]
Thanks for pointing this out @HongminWu !

These bash scripts were actually unneeded; training for the results from the paper used the `scripts/door_task/train_door.py` and `scripts/push_task/train_push.py` Python scripts directly.
